### ISSUE TITLE
Project closed?

### ISSUE THREAD

**Issue by JohnRSim** [wikihouseproject/buildx-editor#27]
Has this JS project been closed for a new one that has yet to be released?

Haven't seen any updates here for 6months but lots of continuous news on JS wikihouse build project.. and jobs for js devs

**Comment by johnrees** [comment]
Hi @JohnRSim, thanks for your interest (and apologies for the radio silence!).

There has been a bit of progress with the buildx editor but it's been in seperate places and needs to be, and will be, consolidated back into a single repository. I'll be sure to notify you and the followers of this repo when that happens.

The recent JS dev posting was for a seperate project that we're taking on related to UK planning laws which we'll be sharing more information about ASAP.

**Comment by JohnRSim** [comment]
@johnrees thanks for the update! 
Looking forward to testing out the new updates!

**Comment by StartupSam** [comment]
Hi - looks like it's been over a year since there's been any activity here. Is there a new repo somewhere, or are there plans to make new code public?

I'd like to contribute if possible (and am not a structural engineer so can't help with Blackbird lol).
